spring.application.name=execution-engine
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/sentinel_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.schema-locations=classpath:schema.sql
mt5.bridge.url=${MT5_BRIDGE_URL:http://localhost:9000/execute}